# Введение 2. Основные термины и определения математического анализа, линейной алгебры и теории вероятностей

### Перемножение матриц

Импортируем нампи

In [40]:
import numpy as np

Используем функцию перемножения матриц из нампи

In [41]:
def matmul(A, B):
    return A.dot(B)

1)

In [42]:
A = np.array([[7,1,-1], [1,-3,5], [-6,2,-2]])
B = np.array([[-9,-6,2], [0,-5,5], [0,5,-7]])
C = matmul(A, B)
print(C)

[[-63 -52  26]
 [ -9  34 -48]
 [ 54  16  12]]


2)

In [43]:
A = np.array([[-9,5,2], [-8,-3,4], [-5,8,-8]])
B = np.array([[1,-5,1], [7,3,1], [-2,4,7]])
C = matmul(A, B)
print(C)

[[ 22  68  10]
 [-37  47  17]
 [ 67  17 -53]]


### Определитель матриц

Используем функцию вычисления определителя из пакета линейной алгебры нампи

In [44]:
def det(A):
    d = np.linalg.det(A)
    return float("%0.2f" % d)

1)

In [45]:
det(np.array([[4,1], [-7,-8]]))

-25.0

2)

In [46]:
det(np.array([[7,2,-9], [9,-2,4], [0,2,-1]]))

-186.0

3)

In [47]:
det(np.array([[1,-7,-3], [4,4,-1], [1,0,0]]))

19.0

4)

In [48]:
det(np.array([[5,5,5,0], [1,4,0,1], [-2,-6,0,1], [0,-6,3,-2]]))

-35.0

### Собственные числа матриц

Используем функцию вычисления собственных чисел и векторов из пакета линейной алгебры нампи

In [49]:
def eig(A):
    return np.linalg.eig(A)

In [50]:
def print_eig(data):
    print("X =", [float("%0.2f" % x) for x in data[0]])
    print("V =", [[float("%0.2f" % x) for x in v] for v in data[1]])

1)

In [51]:
print_eig(eig(np.array([[3,-2], [-5,-1]])))

X = [4.74, -2.74]
V = [[0.75, 0.33], [-0.66, 0.94]]


2)

In [52]:
print_eig(eig(np.array([[6,-3,-2], [0,-6,-2], [-3,3,-1]])))

X = [6.57, -3.0, -4.57]
V = [[-0.94, -0.0, 0.12], [-0.06, 0.55, 0.81], [0.35, -0.83, -0.58]]


### Предел полиномиальных дробей

В заданиях a-d делим числитель и знаменатель на старшую степень. Если встречается косинус или синус, то принимаем за единицу, так как область значений этих функций находится между единицей и минус единицей.

a)

In [53]:
%%latex
$\lim_{x\to\infty} \frac{4x^2+3x}{5x^2+17x-7} = \frac{4}{5}$

<IPython.core.display.Latex object>

b)

In [54]:
%%latex
$\lim_{x\to\infty} \frac{100x^2+17x-3}{x^3+x^2+x+1} = \frac{100}{x} = 0$

<IPython.core.display.Latex object>

c)

In [55]:
%%latex
$\lim_{x\to\infty} \frac{x^2+4x+11+sin(x)}{3x^2+x-2} = \frac{1}{3}$

<IPython.core.display.Latex object>

d)

In [56]:
%%latex
$\lim_{x\to\infty} \frac{7x^2-2x-4+cos(x)}{7x^2-7x+7+sin(x)} = 1$

<IPython.core.display.Latex object>

В заданиях e и f нужно применить второй замечательный предел

e)

In [57]:
%%latex
$\lim_{x\to\infty} (1 + \frac{1}{2x})^{3x} = ((1 + \frac{1}{2x})^{2x})^\frac{3x}{2x} = e^\frac{3}{2}$

<IPython.core.display.Latex object>

f)

In [58]:
%%latex
$\lim_{x\to\infty} (\frac{x-1}{x+1})^{x+2} = (1 + \frac{-2}{x+1})^{x+2} = (1 + \frac{1}{\frac{x+1}{-2}})^{x+2} = (((1 + \frac{1}{\frac{x+1}{-2}})^{\frac{x+1}{-2}}))^{\frac{-2}{x+1}*(x+2)} = e^{-2*\lim_{x\to\infty} \frac{x+2}{x+1}} = e^{-2}$

<IPython.core.display.Latex object>

В задании g нужно разложить arctg и sin в ряд Маклорена

In [59]:
%%latex
$\lim_{x\to 0} \frac{arctg(x) - sin(x)}{x^5} = \frac{x - \frac{x^3}{3} + \frac{x^5}{5} - \frac{x^7}{7} - (x - \frac{x^3}{3!} + \frac{x^5}{5!} - \frac{x^7}{7!})}{x^5} = \frac{\frac{x^3}{3!} - \frac{x^3}{3} + \frac{x^5}{5} - \frac{x^5}{5!} + \frac{x^7}{7!} - \frac{x^7}{7}}{x^5} = \frac{1}{6x^2} - \frac{1}{3x^2} + \frac{1}{5} - \frac{1}{5!} = -\infty$

<IPython.core.display.Latex object>

### Нотация o малое

In [60]:
%%latex
При $x\to 0$ преобразовать $(1+x^4+x^5+o(x^9))*(1+x^3+x^4+o(x^9))$

<IPython.core.display.Latex object>

In [80]:
%%latex
$(1+x^4+x^5+o(x^9))*(1+x^3+x^4+o(x^9)) = 1 + x^3 + x^4 + o(x^9) + x^4 + x^7 + x^8 + x^4*o(x^9) + x^5 + x^8 + x^9 + x^5*o(x^9) + o(x^9) + x^3*o(x^9) + x^4*o(x^9) + o(x^9)*o(x^9) = 1 + x^3 + 2x^4 + x^5 + x^7 + 2x^8 + x^9 + o(x^9) + o(x^{13}) + o(x^{14}) + o(x^{12}) + o(x^{13}) + o(x^{18}) = 1 + x^3 + 2x^4 + x^5 + x^7 + 2x^8 + o(x^9)$

<IPython.core.display.Latex object>

### Матожидание и дисперсия

Матожидание дискретной случайной величины вычисляется по формуле

In [62]:
%%latex
$M[X]=\sum \limits _{{i=1}}^{{\infty }}x_{i}\,p_{i}$

<IPython.core.display.Latex object>

дисперсия

In [63]:
%%latex
$D[X]=\sum \limits _{i=1}^{n}{p_{i}(x_{i}-M[X])^{2}}$

<IPython.core.display.Latex object>

Если случайная величина имеет непрерывное равномерное распределение, то матожидание можно вычислить по формуле

In [64]:
%%latex
$M[X]={\frac {a+b}{2}}$

<IPython.core.display.Latex object>

дисперсия

In [65]:
%%latex
$D[X]={\frac {(b-a)^{2}}{12}}$

<IPython.core.display.Latex object>

In [66]:
def print_md(MD):
    print("M =", float("%0.2f" % MD[0]))
    print("D =", float("%0.2f" % MD[1]))

In [67]:
from functools import reduce

def mdd(X, P):
    M = reduce(lambda m, v: m + (v[0]*v[1]), zip(X,P), 0)
    D = reduce(lambda d, v: d + v[1]*(v[0]-M)**2, zip(X,P), 0)
    return (M,D)

In [68]:
def mdu(a,b):
    return (a+b)/2, ((b-a)**2)/12

a) b)

In [69]:
print_md(mdd([-2,-1,0,1,2,3], [0.1,0.1,0.3,0.2,0.05,0.25]))

M = 0.75
D = 2.59


c)

In [70]:
print_md(mdu(1,4))

M = 2.5
D = 0.75


d)

In [71]:
print_md(mdu(-5,7))

M = 1.0
D = 12.0
