# ДЗ №2

In [32]:
import numpy as np

## Перемножение матриц

In [33]:
data = [
    ("A", [[7,6,5],[-1,-2,-5], [-7,0,-2]], [[6,1,-4],[6,8,8], [-10,8,6]]),
    ("B", [[0,-4,-1],[-2,2,7],[4,6,9]], [[2],[9],[0]])
]

for x in data:
    C = np.array(x[1]).dot(np.array(x[2]))
    print(x[0], "\n", C, "\n")

A 
 [[ 28  95  50]
 [ 32 -57 -42]
 [-22 -23  16]] 

B 
 [[-36]
 [ 14]
 [ 62]] 



## Ранг матрицы

In [34]:
data = [
    ("A", [[4,2,3],[5,2,1],[9,4,4]]),
    ("B", [[3,2,1,5],[6,4,3,7],[9,6,5,9],[3,2,0,8]]),
    ("C", [[1,2,1,1],[0,1,1,1],[1,3,2,2]])
]

for x in data:
    R = np.linalg.matrix_rank(np.array(x[1]))
    print(x[0], R)

A 2
B 2
C 2


## Определитель

In [35]:
data = [
    ("A", [[-3,7,4],[2,-1,2],[3,7,-3]]),
    ("B", [[-1,0,2],[-10,-7,4],[-3,-3,2]]),
    ("C", [[4,-2,1],[-5,0,-1],[-7,2,7]]),
    ("D", [[7,-4,-10,3,1],[7,-9,2,-6,-2],[-3,-8,3,-7,-7],[7,8,-4,2,-8],[0,5,-12,9,3]]),
    ("E", [[-1,-5,2,2],[-5,0,-3,6],[-5,9,-5,8], [-8,-6,-5,6]])
]

for x in data:
    D = np.linalg.det(np.array(x[1]))
    print(x[0], float("%0.2f" % D))


A 185.0
B 20.0
C -86.0
D 0.0
E 20.0


## Собственные числа и вектора

In [36]:
data = [
    ("A", [[2,0,1],[1,1,1],[1,0,2]]),
    ("B", [[1,1,3],[1,5,1],[3,1,1]]),
    ("C", [[2,1,-1,0],[0,0,0,0],[2,0,-1,0],[0,1,0,0]]),
    ("D", [[4,6,0],[-3,-5,0],[-3,-6,0]]),
    ("E", [[10,4,4],[-1,1,0],[-13,-6,-5]])
]

for x in data:
    E = np.linalg.eig(np.array(x[1]))
    print("<", x[0], ">")
    print("X =", [float("%0.2f" % x) for x in E[0]])
    print("V =", [[float("%0.2f" % x) for x in v] for v in E[1]])
    print()

< A >
X = [1.0, 3.0, 1.0]
V = [[0.0, 0.58, -0.71], [1.0, 0.58, 0.0], [0.0, 0.58, 0.71]]

< B >
X = [-2.0, 3.0, 6.0]
V = [[0.71, -0.58, -0.41], [-0.0, 0.58, -0.82], [-0.71, -0.58, -0.41]]

< C >
X = [1.0, 0.0, 0.0, 0.0]
V = [[0.71, 0.45, 0.0, 0.41], [0.0, 0.0, 0.0, 0.0], [0.71, 0.89, 0.0, 0.82], [0.0, 0.0, 1.0, -0.41]]

< D >
X = [0.0, -2.0, 1.0]
V = [[0.0, 0.49, -0.89], [0.0, -0.49, 0.45], [1.0, -0.73, 0.0]]

< E >
X = [3.0, 2.0, 1.0]
V = [[0.6, -0.58, -0.0], [-0.3, 0.58, 0.71], [-0.75, 0.58, -0.71]]

